Добавление библиотеки для сверхвысокоскоростных математических вычислений
extremecodetv/ExtremeCodeOS pull request #55
Opened 2021-10-31 15:02 UTC by KirillAldashkin

Создаю библиотеку для различных математических вычислений. Библиотека может использоваться модульно, так как реализована в виде сервисов (Depedency Injection), поэтому вычисления в среднем на 727% быстрее, чем при использовании нативных функций, которые нельзя "включить частично".
- [X] Инкремент числа
- [ ] Декремент числа
- [X] Инверсия числа
- [ ] Сравнение чисел
- [ ] Сложение чисел
- [ ] Вычитание чисел
- [ ] Умножение чисел
- [ ] Деление чисел
- [ ] Возведение чисел в степень

2021-10-31 15:03 UTC, Airkek commented
> в среднем на 727%

мне уже нравится

2021-10-31 16:19 UTC, lrmpsm53 commented
Проц тащит

2021-11-01 16:11 UTC, Maksim2355 requested changes

2021-11-01 16:11 UTC, Maksim2355 commented on src/Libraries/Math/Math/CompareService.cs
> +            try
Лучше вынести последующие trycatch в блок finally

2021-11-01 16:11 UTC, Maksim2355 commented on src/Libraries/Math/Tests/SimpleOperationsTests.cs
> +                val = -3;
Лучшие придерживаться одинаковых типов. Я бы сделал не Int, а Float

2021-11-01 16:11 UTC, Maksim2355 commented on src/Libraries/Math/Tests/SimpleOperationsTests.cs
> +                Assert.ThrowsException<OverflowException>(() => increment.Increment(ref val));
Лучше не работать с ошибками. Если не вылетает, то норм. Обернуть ес чо все в try

2021-11-01 17:18 UTC, KirillAldashkin commented on src/Libraries/Math/Math/CompareService.cs
> +            try
`return` нельзя делать в блоке `finally` (ошибка компилятора [CS0157](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0157)), поэтому придётся немного подшаманить.

2021-11-05 11:51 UTC, FinIsOro commented
> в среднем на 727% быстрее
WYSI

2021-11-29 14:31 UTC, maxsssssssss commented
Кажется, проект заброшен?

2022-05-15 07:09 UTC, closed without merging